#cloud-config
hostname: coreos2
users:
  - name: core
    passwd: $6$j1E6FdI8$/AW8orxphphWko6K.1btsaehB8ABK1LnPTi6WfEqQRWnYlVwsuxyAYyweSDpzZFdqxvsvPw184cR9470muDQe/
    
write_files:
   - path: "/etc/hosts"
     permissions: 0644
     owner: root:root
     content: |
         127.0.0.1  localhost
         ::1        localhost
         192.168.0.69 coreos1
         192.168.0.70 coreos2
         192.168.0.71 coreos3

coreos:
  units:
    - name: etcd2.service
      command: start
    - name: systemd-networkd.service
      command: stop
    - name: 00-eth0.network
      runtime: true
      content: |
        [Match]
        Name=eth0

        [Network]
        DNS=168.95.1.1
        Address=192.168.0.70/24
        Gateway=192.168.0.2
    - name: down-interfaces.service
      command: start
      content: |
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/ip link set eth0 down
        ExecStart=/usr/bin/ip addr flush dev eth0
    - name: systemd-networkd.service
      command: restart
    - name: settimezone.service
      command: start
      content: |
        [Unit]
        Description=Set the time zone

        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone  Asia/Taipei
        RemainAfterExit=yes
        Type=oneshot

  etcd2:
    name: "node02"
    discovery: https://discovery.etcd.io/b44a63fd67711fc1b19eaf6b18887664
    advertise-client-urls: http://coreos2:2379
    initial-advertise-peer-urls: http://coreos2:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://coreos2:2380

  flannel:
    interface: 192.168.0.70

  units:
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            Restart=always

            [Install]
            WantedBy=multi-user.target

    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            After=etcd2.service
            Requires=etcd2.service

            [Service]
            ExecStartPre= \
            echo "ExecStartPre=/usr/bin/rm -rf /var/lib/etcd2/proxy" > /run/systemd/system/etcd2.service.d/99-restore.conf ;\
            echo 'Environment="ETCD_DISCOVERY="' >> /run/systemd/system/etcd2.service.d/99-restore.conf ;\ 
            echo 'Environment="ETCD_NAME=node02"' >> /run/systemd/system/etcd2.service.d/99-restore.conf ; \
            echo 'Environment="ETCD_INITIAL_CLUSTER=node01=http://coreos1:2380,node02=http://coreos2:2380"' >> /run/systemd/system/etcd2.service.d/99-restore.conf; \
            echo 'Environment="ETCD_INITIAL_CLUSTER_STATE=existing"' >> /run/systemd/system/etcd2.service.d/99-restore.conf; \
            systemctl daemon-reload ;\
            systemctl restart etcd2
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "172.17.0.0/16" }'

            [Install]
            WantedBy=multi-user.target
      command: start

    - name: docker.service
      command: start
      drop-ins:
      - name: 60-docker-wait-for-flannel-config.conf
        content: |
          [Unit]
          After=flanneld.service
          Requires=flanneld.service

          [Service]
          Restart=always

          [Install]
          WantedBy=multi-user.target


    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        Service=docker.service

        [Install]
        WantedBy=sockets.target
